### ISSUE TITLE
QColor::setRgb: RGB parameters out of range

### ISSUE THREAD

**Issue by andrew771211** [kantooon/qradiolink#20]
Finally I Upgraded to ubuntu 17.10 and qradiolink works!

but how I change the colors? the up push buttons ("TX, RX, Config...." )are yellow in a white background 

thanks!
good project!
And

**Comment by kantooon** [comment]
Can you please attach a screenshot? The colours are hardcoded, can't be changed by the user. If the application does not look like in the screenshot, then something is overriding the Qt theme, which may be a bug.

**Comment by andrew771211** [comment]
![screenshot at 2018-01-21 13-18-32](https://user-images.githubusercontent.com/16758847/35194096-b1feee2a-fead-11e7-9c12-fa6f10eaf2d2.png)

On top left: "TX TUNE SPECTRUM..." white background..

**Comment by kantooon** [comment]
Ok, that looks seriously strange. Which window manager are you using? It may be overwriting the Qt theme. LXDE has also given me some headaches because some Qt widgets are displayed differently, like the Repeater, RX, TX buttons not having a background unless hovering.
KDE also displays dials differently, see my screenshot.

**Comment by andrew771211** [comment]
MATE Desktop Environment 1.18.0
